//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VertesiaActivity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VertesiaActivity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key used to authenticate with the Vertesia STS service to obtain a JWT token..
        /// </summary>
        public static string VertesiaUploaderSettings_ApiKey_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string VertesiaUploaderSettings_ApiKey_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ApiKey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URL of the Vertesia API (cv_API_URL). Used as the target for upload and object registration requests..
        /// </summary>
        public static string VertesiaUploaderSettings_ApiUrl_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ApiUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL.
        /// </summary>
        public static string VertesiaUploaderSettings_ApiUrl_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ApiUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type (cv_content_type) used when requesting an upload URL and registering the uploaded object..
        /// </summary>
        public static string VertesiaUploaderSettings_ContentType_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ContentType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string VertesiaUploaderSettings_ContentType_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ContentType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the Vertesia interaction to execute (cv_interaction_id) after the object is ready..
        /// </summary>
        public static string VertesiaUploaderSettings_InteractionId_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_InteractionId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction ID.
        /// </summary>
        public static string VertesiaUploaderSettings_InteractionId_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_InteractionId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps fields from the interaction Results response to custom value names on the child document. Key: field name in Results JSON. Value: custom value name to set on the document..
        /// </summary>
        public static string VertesiaUploaderSettings_ResultMapping_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ResultMapping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Field Mapping.
        /// </summary>
        public static string VertesiaUploaderSettings_ResultMapping_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_ResultMapping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps array fields from the interaction result to table rows on the child document. Key: &quot;array_prefix.field_name&quot; (e.g. &quot;line_items.description&quot;). Value: &quot;TableName.ColumnName&quot; (e.g. &quot;LineItems.Description&quot;). All entries with the same array prefix populate one table, one row per array element..
        /// </summary>
        public static string VertesiaUploaderSettings_TableMapping_Description {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_TableMapping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Mapping.
        /// </summary>
        public static string VertesiaUploaderSettings_TableMapping_Name {
            get {
                return ResourceManager.GetString("VertesiaUploaderSettings_TableMapping_Name", resourceCulture);
            }
        }
        /// <summary>Additional Parameters</summary>
        public static string VertesiaUploaderSettings_AdditionalParameters_Name
        {
            get
            {
                return ResourceManager.GetString("VertesiaUploaderSettings_AdditionalParameters_Name", resourceCulture);
            }
        }

        /// <summary>Additional key/value pairs merged into the interaction request body's "data" object.</summary>
        public static string VertesiaUploaderSettings_AdditionalParameters_Description
        {
            get
            {
                return ResourceManager.GetString("VertesiaUploaderSettings_AdditionalParameters_Description", resourceCulture);
            }
        }
    }
}
